# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'baby7_desktop_tool_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(2047, 1154)
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(12, 11, 205, 81))
        self.label.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgba(255, 255, 255, 1);\n"
"    background-color: rgba(255, 255, 255, 1);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.date_label = QtWidgets.QLabel(Form)
        self.date_label.setGeometry(QtCore.QRect(30, 21, 171, 61))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.date_label.setFont(font)
        self.date_label.setObjectName("date_label")
        self.time_label = QtWidgets.QLabel(Form)
        self.time_label.setGeometry(QtCore.QRect(224, 29, 191, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.time_label.setFont(font)
        self.time_label.setStyleSheet("color: rgb(255,255,255);")
        self.time_label.setAlignment(QtCore.Qt.AlignCenter)
        self.time_label.setObjectName("time_label")
        self.push_button_reading = QtWidgets.QPushButton(Form)
        self.push_button_reading.setGeometry(QtCore.QRect(382, 600, 51, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.push_button_reading.setFont(font)
        self.push_button_reading.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    border-color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgba(255, 255, 255, 0.5);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.push_button_reading.setObjectName("push_button_reading")
        self.push_button_60s_news = QtWidgets.QPushButton(Form)
        self.push_button_60s_news.setGeometry(QtCore.QRect(382, 500, 51, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.push_button_60s_news.setFont(font)
        self.push_button_60s_news.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    border-color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgba(255, 255, 255, 0.5);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.push_button_60s_news.setObjectName("push_button_60s_news")
        self.push_button_weibo_info = QtWidgets.QPushButton(Form)
        self.push_button_weibo_info.setGeometry(QtCore.QRect(382, 450, 51, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.push_button_weibo_info.setFont(font)
        self.push_button_weibo_info.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 0px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgba(0, 0, 0, 1);\n"
"    background-color: rgba(255, 255, 255, 1);")
        self.push_button_weibo_info.setObjectName("push_button_weibo_info")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(12, 103, 421, 161))
        self.label_5.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgba(255, 255, 255, 0.8);\n"
"    background-color: rgba(255, 255, 255, 1);\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.weather_image_label_1 = QtWidgets.QLabel(Form)
        self.weather_image_label_1.setGeometry(QtCore.QRect(50, 112, 51, 51))
        self.weather_image_label_1.setText("")
        self.weather_image_label_1.setPixmap(QtGui.QPixmap("img/weather/blue80_1_1.png"))
        self.weather_image_label_1.setScaledContents(True)
        self.weather_image_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_image_label_1.setObjectName("weather_image_label_1")
        self.weather_image_label_2 = QtWidgets.QLabel(Form)
        self.weather_image_label_2.setGeometry(QtCore.QRect(55, 172, 31, 31))
        self.weather_image_label_2.setText("")
        self.weather_image_label_2.setPixmap(QtGui.QPixmap("img/weather/blue80_1_1.png"))
        self.weather_image_label_2.setScaledContents(True)
        self.weather_image_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_image_label_2.setObjectName("weather_image_label_2")
        self.weather_image_label_3 = QtWidgets.QLabel(Form)
        self.weather_image_label_3.setGeometry(QtCore.QRect(156, 172, 31, 31))
        self.weather_image_label_3.setText("")
        self.weather_image_label_3.setPixmap(QtGui.QPixmap("img/weather/blue80_1_1.png"))
        self.weather_image_label_3.setScaledContents(True)
        self.weather_image_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_image_label_3.setObjectName("weather_image_label_3")
        self.weather_image_label_4 = QtWidgets.QLabel(Form)
        self.weather_image_label_4.setGeometry(QtCore.QRect(255, 172, 31, 31))
        self.weather_image_label_4.setText("")
        self.weather_image_label_4.setPixmap(QtGui.QPixmap("img/weather/blue80_1_1.png"))
        self.weather_image_label_4.setScaledContents(True)
        self.weather_image_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_image_label_4.setObjectName("weather_image_label_4")
        self.weather_image_label_5 = QtWidgets.QLabel(Form)
        self.weather_image_label_5.setGeometry(QtCore.QRect(357, 172, 31, 31))
        self.weather_image_label_5.setText("")
        self.weather_image_label_5.setPixmap(QtGui.QPixmap("img/weather/blue80_1_1.png"))
        self.weather_image_label_5.setScaledContents(True)
        self.weather_image_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_image_label_5.setObjectName("weather_image_label_5")
        self.weather_info_label_2 = QtWidgets.QLabel(Form)
        self.weather_info_label_2.setGeometry(QtCore.QRect(29, 202, 85, 35))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.weather_info_label_2.setFont(font)
        self.weather_info_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_info_label_2.setObjectName("weather_info_label_2")
        self.weather_temp_label_2 = QtWidgets.QLabel(Form)
        self.weather_temp_label_2.setGeometry(QtCore.QRect(28, 235, 81, 25))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.weather_temp_label_2.setFont(font)
        self.weather_temp_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_temp_label_2.setObjectName("weather_temp_label_2")
        self.weather_info_label_3 = QtWidgets.QLabel(Form)
        self.weather_info_label_3.setGeometry(QtCore.QRect(120, 202, 85, 35))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.weather_info_label_3.setFont(font)
        self.weather_info_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_info_label_3.setObjectName("weather_info_label_3")
        self.weather_temp_label_3 = QtWidgets.QLabel(Form)
        self.weather_temp_label_3.setGeometry(QtCore.QRect(129, 235, 81, 25))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.weather_temp_label_3.setFont(font)
        self.weather_temp_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_temp_label_3.setObjectName("weather_temp_label_3")
        self.weather_info_label_4 = QtWidgets.QLabel(Form)
        self.weather_info_label_4.setGeometry(QtCore.QRect(229, 202, 85, 35))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.weather_info_label_4.setFont(font)
        self.weather_info_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_info_label_4.setObjectName("weather_info_label_4")
        self.weather_temp_label_4 = QtWidgets.QLabel(Form)
        self.weather_temp_label_4.setGeometry(QtCore.QRect(228, 235, 81, 25))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.weather_temp_label_4.setFont(font)
        self.weather_temp_label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_temp_label_4.setObjectName("weather_temp_label_4")
        self.weather_info_label_5 = QtWidgets.QLabel(Form)
        self.weather_info_label_5.setGeometry(QtCore.QRect(331, 202, 85, 35))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.weather_info_label_5.setFont(font)
        self.weather_info_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_info_label_5.setObjectName("weather_info_label_5")
        self.weather_temp_label_5 = QtWidgets.QLabel(Form)
        self.weather_temp_label_5.setGeometry(QtCore.QRect(329, 235, 81, 25))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.weather_temp_label_5.setFont(font)
        self.weather_temp_label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.weather_temp_label_5.setObjectName("weather_temp_label_5")
        self.weather_info_label_1 = QtWidgets.QLabel(Form)
        self.weather_info_label_1.setGeometry(QtCore.QRect(116, 115, 161, 20))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.weather_info_label_1.setFont(font)
        self.weather_info_label_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weather_info_label_1.setObjectName("weather_info_label_1")
        self.weather_temp_label_1 = QtWidgets.QLabel(Form)
        self.weather_temp_label_1.setGeometry(QtCore.QRect(116, 137, 81, 20))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.weather_temp_label_1.setFont(font)
        self.weather_temp_label_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.weather_temp_label_1.setObjectName("weather_temp_label_1")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(30, 163, 390, 1))
        self.line_2.setStyleSheet("    color: rgba(0,0,0,0.8);\n"
"    border-color: rgba(0,0,0,0.8);\n"
"    background-color: rgba(0,0,0,0.8);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.push_button_schedule = QtWidgets.QPushButton(Form)
        self.push_button_schedule.setGeometry(QtCore.QRect(229, 275, 205, 154))
        self.push_button_schedule.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgba(255, 255, 255, 1);\n"
"    background-color: rgba(255, 255, 255, 1);")
        self.push_button_schedule.setText("")
        self.push_button_schedule.setObjectName("push_button_schedule")
        self.daily_schedule_label = QtWidgets.QLabel(Form)
        self.daily_schedule_label.setGeometry(QtCore.QRect(250, 308, 171, 115))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.daily_schedule_label.setFont(font)
        self.daily_schedule_label.setStyleSheet("")
        self.daily_schedule_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.daily_schedule_label.setObjectName("daily_schedule_label")
        self.push_button_looking = QtWidgets.QPushButton(Form)
        self.push_button_looking.setGeometry(QtCore.QRect(382, 550, 51, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.push_button_looking.setFont(font)
        self.push_button_looking.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    border-color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgba(255, 255, 255, 0.5);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.push_button_looking.setObjectName("push_button_looking")
        self.push_button_info = QtWidgets.QPushButton(Form)
        self.push_button_info.setGeometry(QtCore.QRect(12, 440, 381, 581))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setBold(True)
        font.setWeight(75)
        self.push_button_info.setFont(font)
        self.push_button_info.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgba(255, 255, 255, 1);\n"
"    background-color: rgba(255, 255, 255, 1);")
        self.push_button_info.setText("")
        self.push_button_info.setObjectName("push_button_info")
        self.scroll_area = QtWidgets.QScrollArea(Form)
        self.scroll_area.setGeometry(QtCore.QRect(1260, 800, 151, 161))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setBold(True)
        font.setWeight(75)
        self.scroll_area.setFont(font)
        self.scroll_area.setStyleSheet("border-style: solid;\n"
"border-radius: 10px;\n"
"border: 1px groove gray;\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.scroll_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scroll_area.setLineWidth(1)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 149, 159))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.push_button_restart = QtWidgets.QPushButton(Form)
        self.push_button_restart.setGeometry(QtCore.QRect(183, 395, 31, 31))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.push_button_restart.setFont(font)
        self.push_button_restart.setStyleSheet("background:rgba(0,0,0,0);color: #000;")
        self.push_button_restart.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/drinking/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_button_restart.setIcon(icon)
        self.push_button_restart.setIconSize(QtCore.QSize(18, 18))
        self.push_button_restart.setObjectName("push_button_restart")
        self.label_add = QtWidgets.QPushButton(Form)
        self.label_add.setGeometry(QtCore.QRect(15, 393, 31, 31))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_add.setFont(font)
        self.label_add.setStyleSheet("background:rgba(0,0,0,0);color: #000;")
        self.label_add.setObjectName("label_add")
        self.center_label_2 = QtWidgets.QLabel(Form)
        self.center_label_2.setGeometry(QtCore.QRect(63, 320, 81, 81))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(45)
        font.setBold(False)
        font.setWeight(50)
        self.center_label_2.setFont(font)
        self.center_label_2.setText("")
        self.center_label_2.setObjectName("center_label_2")
        self.looking_area = QtWidgets.QScrollArea(Form)
        self.looking_area.setGeometry(QtCore.QRect(750, 780, 241, 181))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setBold(True)
        font.setWeight(75)
        self.looking_area.setFont(font)
        self.looking_area.setStyleSheet("border-style: solid;\n"
"border-radius: 10px;\n"
"border: 1px groove gray;\n"
"color: rgb(0, 0, 0);\n"
"border-color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 255, 255);")
        self.looking_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.looking_area.setLineWidth(1)
        self.looking_area.setWidgetResizable(True)
        self.looking_area.setObjectName("looking_area")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 239, 179))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.push_button_looking_fish = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.push_button_looking_fish.setGeometry(QtCore.QRect(190, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.push_button_looking_fish.setFont(font)
        self.push_button_looking_fish.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);")
        self.push_button_looking_fish.setObjectName("push_button_looking_fish")
        self.push_button_looking_everyday = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.push_button_looking_everyday.setGeometry(QtCore.QRect(30, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.push_button_looking_everyday.setFont(font)
        self.push_button_looking_everyday.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);")
        self.push_button_looking_everyday.setObjectName("push_button_looking_everyday")
        self.looking_area.setWidget(self.scrollAreaWidgetContents_2)
        self.reading_area = QtWidgets.QScrollArea(Form)
        self.reading_area.setGeometry(QtCore.QRect(990, 780, 231, 231))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setBold(True)
        font.setWeight(75)
        self.reading_area.setFont(font)
        self.reading_area.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"border-color: rgba(255, 255, 255, 1);\n"
"background-color: rgba(255, 255, 255, 1);")
        self.reading_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.reading_area.setLineWidth(1)
        self.reading_area.setWidgetResizable(True)
        self.reading_area.setObjectName("reading_area")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 229, 229))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.push_button_reading_life = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.push_button_reading_life.setGeometry(QtCore.QRect(190, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.push_button_reading_life.setFont(font)
        self.push_button_reading_life.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);")
        self.push_button_reading_life.setObjectName("push_button_reading_life")
        self.push_button_reading_history = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.push_button_reading_history.setGeometry(QtCore.QRect(30, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.push_button_reading_history.setFont(font)
        self.push_button_reading_history.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);")
        self.push_button_reading_history.setObjectName("push_button_reading_history")
        self.push_button_reading_rainbow = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.push_button_reading_rainbow.setGeometry(QtCore.QRect(190, 80, 141, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.push_button_reading_rainbow.setFont(font)
        self.push_button_reading_rainbow.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);")
        self.push_button_reading_rainbow.setObjectName("push_button_reading_rainbow")
        self.push_button_reading_riddle = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.push_button_reading_riddle.setGeometry(QtCore.QRect(30, 80, 141, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.push_button_reading_riddle.setFont(font)
        self.push_button_reading_riddle.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);")
        self.push_button_reading_riddle.setObjectName("push_button_reading_riddle")
        self.push_button_reading_morning = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.push_button_reading_morning.setGeometry(QtCore.QRect(30, 140, 141, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.push_button_reading_morning.setFont(font)
        self.push_button_reading_morning.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);")
        self.push_button_reading_morning.setObjectName("push_button_reading_morning")
        self.push_button_reading_night = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.push_button_reading_night.setGeometry(QtCore.QRect(190, 140, 141, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.push_button_reading_night.setFont(font)
        self.push_button_reading_night.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);")
        self.push_button_reading_night.setObjectName("push_button_reading_night")
        self.push_button_reading_chicken_1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.push_button_reading_chicken_1.setGeometry(QtCore.QRect(30, 200, 141, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.push_button_reading_chicken_1.setFont(font)
        self.push_button_reading_chicken_1.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);")
        self.push_button_reading_chicken_1.setObjectName("push_button_reading_chicken_1")
        self.push_button_reading_chicken_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.push_button_reading_chicken_2.setGeometry(QtCore.QRect(190, 200, 141, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.push_button_reading_chicken_2.setFont(font)
        self.push_button_reading_chicken_2.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);")
        self.push_button_reading_chicken_2.setObjectName("push_button_reading_chicken_2")
        self.push_button_reading_cheesy_love = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.push_button_reading_cheesy_love.setGeometry(QtCore.QRect(30, 260, 141, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.push_button_reading_cheesy_love.setFont(font)
        self.push_button_reading_cheesy_love.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);")
        self.push_button_reading_cheesy_love.setObjectName("push_button_reading_cheesy_love")
        self.reading_area.setWidget(self.scrollAreaWidgetContents_3)
        self.push_button_todo = QtWidgets.QPushButton(Form)
        self.push_button_todo.setGeometry(QtCore.QRect(382, 650, 51, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.push_button_todo.setFont(font)
        self.push_button_todo.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    border-color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgba(255, 255, 255, 0.5);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.push_button_todo.setObjectName("push_button_todo")
        self.push_button_novel = QtWidgets.QPushButton(Form)
        self.push_button_novel.setGeometry(QtCore.QRect(382, 700, 51, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.push_button_novel.setFont(font)
        self.push_button_novel.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    border-color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgba(255, 255, 255, 0.5);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.push_button_novel.setObjectName("push_button_novel")
        self.push_button_game = QtWidgets.QPushButton(Form)
        self.push_button_game.setGeometry(QtCore.QRect(382, 750, 51, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.push_button_game.setFont(font)
        self.push_button_game.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    border-color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgba(255, 255, 255, 0.5);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.push_button_game.setObjectName("push_button_game")
        self.push_button_setting = QtWidgets.QPushButton(Form)
        self.push_button_setting.setGeometry(QtCore.QRect(382, 800, 51, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.push_button_setting.setFont(font)
        self.push_button_setting.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    border-color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgba(255, 255, 255, 0.5);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.push_button_setting.setObjectName("push_button_setting")
        self.push_button_schedule_2 = QtWidgets.QPushButton(Form)
        self.push_button_schedule_2.setGeometry(QtCore.QRect(255, 29, 47, 47))
        self.push_button_schedule_2.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgba(0, 0, 0, 0.3);\n"
"    background-color: rgba(0, 0, 0, 0.3);")
        self.push_button_schedule_2.setText("")
        self.push_button_schedule_2.setObjectName("push_button_schedule_2")
        self.push_button_schedule_3 = QtWidgets.QPushButton(Form)
        self.push_button_schedule_3.setGeometry(QtCore.QRect(307, 29, 47, 47))
        self.push_button_schedule_3.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgba(0, 0, 0, 0.3);\n"
"    background-color: rgba(0, 0, 0, 0.3);")
        self.push_button_schedule_3.setText("")
        self.push_button_schedule_3.setObjectName("push_button_schedule_3")
        self.push_button_schedule_4 = QtWidgets.QPushButton(Form)
        self.push_button_schedule_4.setGeometry(QtCore.QRect(359, 29, 47, 47))
        self.push_button_schedule_4.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgba(0, 0, 0, 0.3);\n"
"    background-color: rgba(0, 0, 0, 0.3);")
        self.push_button_schedule_4.setText("")
        self.push_button_schedule_4.setObjectName("push_button_schedule_4")
        self.line_top_2 = QtWidgets.QFrame(Form)
        self.line_top_2.setGeometry(QtCore.QRect(239, 52, 180, 1))
        self.line_top_2.setStyleSheet("    color: #FFFFFF;\n"
"    border-color: #FFFFFF;\n"
"    background-color: #FFFFFF;")
        self.line_top_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_top_2.setLineWidth(2)
        self.line_top_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_top_2.setObjectName("line_top_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(229, 11, 205, 81))
        self.label_2.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgba(255, 255, 255, 1);\n"
"    background-color: rgba(255, 255, 255, 1);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.push_button_about = QtWidgets.QPushButton(Form)
        self.push_button_about.setGeometry(QtCore.QRect(382, 850, 51, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.push_button_about.setFont(font)
        self.push_button_about.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    border-color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgba(255, 255, 255, 0.5);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.push_button_about.setObjectName("push_button_about")
        self.top_area = QtWidgets.QScrollArea(Form)
        self.top_area.setGeometry(QtCore.QRect(730, 10, 398, 581))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setBold(True)
        font.setWeight(75)
        self.top_area.setFont(font)
        self.top_area.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 1);")
        self.top_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_area.setLineWidth(1)
        self.top_area.setWidgetResizable(True)
        self.top_area.setObjectName("top_area")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 396, 579))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.weibo_text_browser = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_6)
        self.weibo_text_browser.setGeometry(QtCore.QRect(10, 0, 371, 535))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.weibo_text_browser.setFont(font)
        self.weibo_text_browser.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 0px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgba(255, 255, 255, 0);\n"
"    background-color: rgba(255, 255, 255, 0);")
        self.weibo_text_browser.setObjectName("weibo_text_browser")
        self.push_button_top_baidu = QtWidgets.QPushButton(self.scrollAreaWidgetContents_6)
        self.push_button_top_baidu.setGeometry(QtCore.QRect(70, 540, 51, 31))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.push_button_top_baidu.setFont(font)
        self.push_button_top_baidu.setStyleSheet("QPushButton {\n"
"    border-radius: 0px;\n"
"    background: rgb(255, 255, 255);\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: solid;\n"
"    border: 2px solid #000;\n"
"    border-top-color: #ffffff;\n"
"    border-bottom-color: #000;\n"
"    border-left-color: #000;\n"
"    border-right-color: #000;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #306eff;\n"
"}")
        self.push_button_top_baidu.setObjectName("push_button_top_baidu")
        self.push_button_top_tencent = QtWidgets.QPushButton(self.scrollAreaWidgetContents_6)
        self.push_button_top_tencent.setGeometry(QtCore.QRect(310, 540, 51, 31))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.push_button_top_tencent.setFont(font)
        self.push_button_top_tencent.setStyleSheet("QPushButton {\n"
"    border-radius: 0px;\n"
"    background: rgb(255, 255, 255);\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: solid;\n"
"    border: 2px solid #000;\n"
"    border-top-color: #ffffff;\n"
"    border-bottom-color: #000;\n"
"    border-left-color: #000;\n"
"    border-right-color: #000;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #fedc1c;\n"
"}")
        self.push_button_top_tencent.setObjectName("push_button_top_tencent")
        self.line_top = QtWidgets.QFrame(self.scrollAreaWidgetContents_6)
        self.line_top.setGeometry(QtCore.QRect(0, 540, 398, 2))
        self.line_top.setStyleSheet("    color: #000;\n"
"    border-color: #000;\n"
"    background-color: #000;")
        self.line_top.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_top.setLineWidth(2)
        self.line_top.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_top.setObjectName("line_top")
        self.push_button_top_douyin = QtWidgets.QPushButton(self.scrollAreaWidgetContents_6)
        self.push_button_top_douyin.setGeometry(QtCore.QRect(250, 540, 51, 31))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.push_button_top_douyin.setFont(font)
        self.push_button_top_douyin.setStyleSheet("QPushButton {\n"
"    border-radius: 0px;\n"
"    background: rgb(255, 255, 255);\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: solid;\n"
"    border: 2px solid #000;\n"
"    border-top-color: #ffffff;\n"
"    border-bottom-color: #000;\n"
"    border-left-color: #000;\n"
"    border-right-color: #000;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #ff1752;\n"
"}")
        self.push_button_top_douyin.setObjectName("push_button_top_douyin")
        self.push_button_top_zhihu = QtWidgets.QPushButton(self.scrollAreaWidgetContents_6)
        self.push_button_top_zhihu.setGeometry(QtCore.QRect(190, 540, 51, 31))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.push_button_top_zhihu.setFont(font)
        self.push_button_top_zhihu.setStyleSheet("QPushButton {\n"
"    border-radius: 0px;\n"
"    background: rgb(255, 255, 255);\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: solid;\n"
"    border: 2px solid #000;\n"
"    border-top-color: #ffffff;\n"
"    border-bottom-color: #000;\n"
"    border-left-color: #000;\n"
"    border-right-color: #000;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #00a3ff;\n"
"}")
        self.push_button_top_zhihu.setObjectName("push_button_top_zhihu")
        self.push_button_top_bilibili = QtWidgets.QPushButton(self.scrollAreaWidgetContents_6)
        self.push_button_top_bilibili.setGeometry(QtCore.QRect(130, 540, 51, 31))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.push_button_top_bilibili.setFont(font)
        self.push_button_top_bilibili.setStyleSheet("QPushButton {\n"
"    border-radius: 0px;\n"
"    background: rgb(255, 255, 255);\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: solid;\n"
"    border: 2px solid #000;\n"
"    border-top-color: #ffffff;\n"
"    border-bottom-color: #000;\n"
"    border-left-color: #000;\n"
"    border-right-color: #000;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #F58CAB;\n"
"}")
        self.push_button_top_bilibili.setObjectName("push_button_top_bilibili")
        self.push_button_top_weibo = QtWidgets.QPushButton(self.scrollAreaWidgetContents_6)
        self.push_button_top_weibo.setGeometry(QtCore.QRect(10, 540, 51, 31))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.push_button_top_weibo.setFont(font)
        self.push_button_top_weibo.setStyleSheet("QPushButton {\n"
"    border-radius: 0px;\n"
"    background: rgb(255, 255, 255);\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    border-style: solid;\n"
"    border: 2px solid #000;\n"
"    border-top-color: #ffffff;\n"
"    border-bottom-color: #000;\n"
"    border-left-color: #000;\n"
"    border-right-color: #000;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: solid;\n"
"    border: 2px solid #000;\n"
"    border-top-color: #ffffff;\n"
"    border-bottom-color: #000;\n"
"    border-left-color: #000;\n"
"    border-right-color: #000;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}")
        self.push_button_top_weibo.setFlat(False)
        self.push_button_top_weibo.setObjectName("push_button_top_weibo")
        self.push_button_top_refresh = QtWidgets.QPushButton(self.scrollAreaWidgetContents_6)
        self.push_button_top_refresh.setGeometry(QtCore.QRect(310, 5, 51, 23))
        self.push_button_top_refresh.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);")
        self.push_button_top_refresh.setObjectName("push_button_top_refresh")
        self.weibo_text_browser.raise_()
        self.push_button_top_baidu.raise_()
        self.push_button_top_tencent.raise_()
        self.push_button_top_douyin.raise_()
        self.push_button_top_zhihu.raise_()
        self.push_button_top_bilibili.raise_()
        self.line_top.raise_()
        self.push_button_top_weibo.raise_()
        self.push_button_top_refresh.raise_()
        self.top_area.setWidget(self.scrollAreaWidgetContents_6)
        self.push_button_copy_bottom = QtWidgets.QPushButton(Form)
        self.push_button_copy_bottom.setGeometry(QtCore.QRect(1440, 650, 151, 131))
        self.push_button_copy_bottom.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgba(255, 255, 255, 1);")
        self.push_button_copy_bottom.setText("")
        self.push_button_copy_bottom.setObjectName("push_button_copy_bottom")
        self.todo_area = QtWidgets.QScrollArea(Form)
        self.todo_area.setGeometry(QtCore.QRect(1140, 10, 376, 581))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setBold(True)
        font.setWeight(75)
        self.todo_area.setFont(font)
        self.todo_area.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"border-color: rgba(255, 255, 255, 0);\n"
"background-color: rgba(255, 255, 255, 1);")
        self.todo_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.todo_area.setLineWidth(1)
        self.todo_area.setWidgetResizable(True)
        self.todo_area.setObjectName("todo_area")
        self.scrollAreaWidgetContents_10 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_10.setGeometry(QtCore.QRect(0, 0, 374, 579))
        self.scrollAreaWidgetContents_10.setObjectName("scrollAreaWidgetContents_10")
        self.push_button_todo_ok = QtWidgets.QPushButton(self.scrollAreaWidgetContents_10)
        self.push_button_todo_ok.setGeometry(QtCore.QRect(70, 540, 51, 31))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.push_button_todo_ok.setFont(font)
        self.push_button_todo_ok.setStyleSheet("QPushButton {\n"
"    border-radius: 0px;\n"
"    background: rgb(255, 255, 255);\n"
"    border-bottom-color: rgb(255, 255, 255);\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: solid;\n"
"    border: 2px solid #000;\n"
"    border-top-color: #ffffff;\n"
"    border-bottom-color: #000;\n"
"    border-left-color: #000;\n"
"    border-right-color: #000;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    color: #00a3ff;\n"
"}")
        self.push_button_todo_ok.setObjectName("push_button_todo_ok")
        self.line_top_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_10)
        self.line_top_4.setGeometry(QtCore.QRect(2, 540, 376, 2))
        self.line_top_4.setStyleSheet("    color: #000;\n"
"    border-color: #000;\n"
"    background-color: #000;")
        self.line_top_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_top_4.setLineWidth(2)
        self.line_top_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_top_4.setObjectName("line_top_4")
        self.push_button_todo_todo = QtWidgets.QPushButton(self.scrollAreaWidgetContents_10)
        self.push_button_todo_todo.setGeometry(QtCore.QRect(10, 540, 51, 31))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.push_button_todo_todo.setFont(font)
        self.push_button_todo_todo.setStyleSheet("QPushButton {\n"
"    border-radius: 0px;\n"
"    background: rgb(255, 255, 255);\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    border-style: solid;\n"
"    border: 2px solid #000;\n"
"    border-top-color: #ffffff;\n"
"    border-bottom-color: #000;\n"
"    border-left-color: #000;\n"
"    border-right-color: #000;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: solid;\n"
"    border: 2px solid #000;\n"
"    border-top-color: #ffffff;\n"
"    border-bottom-color: #000;\n"
"    border-left-color: #000;\n"
"    border-right-color: #000;\n"
"    border-bottom-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"}")
        self.push_button_todo_todo.setFlat(False)
        self.push_button_todo_todo.setObjectName("push_button_todo_todo")
        self.todo_list_widget_todo = QtWidgets.QListWidget(self.scrollAreaWidgetContents_10)
        self.todo_list_widget_todo.setGeometry(QtCore.QRect(0, 30, 376, 511))
        self.todo_list_widget_todo.setAutoScroll(True)
        self.todo_list_widget_todo.setAutoScrollMargin(16)
        self.todo_list_widget_todo.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.todo_list_widget_todo.setObjectName("todo_list_widget_todo")
        self.push_button_todo_add = QtWidgets.QPushButton(self.scrollAreaWidgetContents_10)
        self.push_button_todo_add.setGeometry(QtCore.QRect(1, 4, 368, 24))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(15)
        self.push_button_todo_add.setFont(font)
        self.push_button_todo_add.setStyleSheet("QPushButton {\n"
"    color: rgb(0, 195, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(234,244,252);\n"
"    border:1px solid rgb(44,169,225);\n"
"}")
        self.push_button_todo_add.setObjectName("push_button_todo_add")
        self.line_18 = QtWidgets.QFrame(self.scrollAreaWidgetContents_10)
        self.line_18.setGeometry(QtCore.QRect(0, 30, 376, 1))
        self.line_18.setStyleSheet("    color: rgba(200, 200, 200, 0.3);\n"
"    border-color: rgba(200, 200, 200, 0.3);\n"
"    background-color: rgba(200, 200, 200, 0.3);")
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.todo_list_widget_success = QtWidgets.QListWidget(self.scrollAreaWidgetContents_10)
        self.todo_list_widget_success.setGeometry(QtCore.QRect(0, 30, 376, 511))
        self.todo_list_widget_success.setAutoScroll(True)
        self.todo_list_widget_success.setAutoScrollMargin(16)
        self.todo_list_widget_success.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.todo_list_widget_success.setObjectName("todo_list_widget_success")
        self.todo_area.setWidget(self.scrollAreaWidgetContents_10)
        self.push_button_drink = QtWidgets.QPushButton(Form)
        self.push_button_drink.setGeometry(QtCore.QRect(12, 275, 205, 154))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setBold(False)
        font.setWeight(50)
        self.push_button_drink.setFont(font)
        self.push_button_drink.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgba(255, 255, 255, 1);\n"
"    background-color: rgba(255, 255, 255, 1);")
        self.push_button_drink.setText("")
        self.push_button_drink.setObjectName("push_button_drink")
        self.daily_schedule_today = QtWidgets.QLabel(Form)
        self.daily_schedule_today.setGeometry(QtCore.QRect(250, 284, 171, 22))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.daily_schedule_today.setFont(font)
        self.daily_schedule_today.setStyleSheet("")
        self.daily_schedule_today.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.daily_schedule_today.setObjectName("daily_schedule_today")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(240, 308, 180, 1))
        self.line_3.setStyleSheet("    color: rgba(0,0,0,0.8);\n"
"    border-color: rgba(0,0,0,0.8);\n"
"    background-color: rgba(0,0,0,0.8);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.weather_position_label = QtWidgets.QPushButton(Form)
        self.weather_position_label.setGeometry(QtCore.QRect(350, 120, 61, 21))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.weather_position_label.setFont(font)
        self.weather_position_label.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"}")
        self.weather_position_label.setObjectName("weather_position_label")
        self.push_button_drinking_history = QtWidgets.QPushButton(Form)
        self.push_button_drinking_history.setGeometry(QtCore.QRect(15, 278, 31, 31))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.push_button_drinking_history.setFont(font)
        self.push_button_drinking_history.setStyleSheet("background:rgba(0,0,0,0);color: #000;")
        self.push_button_drinking_history.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/drinking/history.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_button_drinking_history.setIcon(icon1)
        self.push_button_drinking_history.setIconSize(QtCore.QSize(18, 18))
        self.push_button_drinking_history.setObjectName("push_button_drinking_history")
        self.push_button_drinking_setting = QtWidgets.QPushButton(Form)
        self.push_button_drinking_setting.setGeometry(QtCore.QRect(183, 278, 31, 31))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.push_button_drinking_setting.setFont(font)
        self.push_button_drinking_setting.setStyleSheet("background:rgba(0,0,0,0);color: #000;")
        self.push_button_drinking_setting.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/drinking/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.push_button_drinking_setting.setIcon(icon2)
        self.push_button_drinking_setting.setIconSize(QtCore.QSize(18, 18))
        self.push_button_drinking_setting.setObjectName("push_button_drinking_setting")
        self.push_button_exit = QtWidgets.QPushButton(Form)
        self.push_button_exit.setGeometry(QtCore.QRect(382, 970, 51, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.push_button_exit.setFont(font)
        self.push_button_exit.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    border-color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgba(255, 255, 255, 0.5);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.push_button_exit.setObjectName("push_button_exit")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(1430, 790, 141, 261))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 139, 259))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_5)
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setGeometry(QtCore.QRect(1652, 126, 231, 21))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("border: 0px solid #FF8D16;\n"
"border-radius: 0px;\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_18.setObjectName("label_18")
        self.line_17 = QtWidgets.QFrame(Form)
        self.line_17.setGeometry(QtCore.QRect(1600, 116, 6, 42))
        self.line_17.setStyleSheet("    border-style: solid;\n"
"    border-radius: 3px;\n"
"    color: rgba(164, 207, 48,0.8);\n"
"    border-color: rgba(164, 207, 48, 0.8);\n"
"    background-color: rgba(164, 207, 48,0.8);")
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.label_20 = QtWidgets.QLabel(Form)
        self.label_20.setGeometry(QtCore.QRect(1934, 72, 25, 25))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(166, 166, 166);")
        self.label_20.setObjectName("label_20")
        self.push_button_reading_cheesy_love_13 = QtWidgets.QPushButton(Form)
        self.push_button_reading_cheesy_love_13.setGeometry(QtCore.QRect(1628, 76, 18, 18))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.push_button_reading_cheesy_love_13.setFont(font)
        self.push_button_reading_cheesy_love_13.setStyleSheet("    border-style: solid;\n"
"    border-radius: 9px;\n"
"    border: 1px groove #000;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgba(0, 0, 0, 0.5);\n"
"    background-color: rgb(255, 255, 255);")
        self.push_button_reading_cheesy_love_13.setText("")
        self.push_button_reading_cheesy_love_13.setIconSize(QtCore.QSize(14, 14))
        self.push_button_reading_cheesy_love_13.setObjectName("push_button_reading_cheesy_love_13")
        self.line_12 = QtWidgets.QFrame(Form)
        self.line_12.setGeometry(QtCore.QRect(1598, 110, 370, 1))
        self.line_12.setStyleSheet("    color: rgba(200, 200, 200, 0.3);\n"
"    border-color: rgba(200, 200, 200, 0.3);\n"
"    background-color: rgba(200, 200, 200, 0.3);")
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_14 = QtWidgets.QFrame(Form)
        self.line_14.setGeometry(QtCore.QRect(1600, 2, 6, 53))
        self.line_14.setStyleSheet("    border-style: solid;\n"
"    border-radius: 3px;\n"
"    color: rgba(212, 63, 54,0.8);\n"
"    border-color: rgba(212, 63, 54, 0.8);\n"
"    background-color: rgba(212, 63, 54,0.8);")
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(1652, 7, 231, 21))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("border: 0px solid #FF8D16;\n"
"border-radius: 0px;\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_16.setObjectName("label_16")
        self.label_19 = QtWidgets.QLabel(Form)
        self.label_19.setGeometry(QtCore.QRect(1934, 5, 25, 25))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(166, 166, 166);")
        self.label_19.setObjectName("label_19")
        self.push_button_reading_cheesy_love_14 = QtWidgets.QPushButton(Form)
        self.push_button_reading_cheesy_love_14.setGeometry(QtCore.QRect(1628, 128, 18, 18))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.push_button_reading_cheesy_love_14.setFont(font)
        self.push_button_reading_cheesy_love_14.setStyleSheet("    border-style: solid;\n"
"    border-radius: 9px;\n"
"    border: 1px groove #000;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgba(0, 0, 0, 0.5);\n"
"    background-color: rgb(255, 255, 255);")
        self.push_button_reading_cheesy_love_14.setText("")
        self.push_button_reading_cheesy_love_14.setIconSize(QtCore.QSize(14, 14))
        self.push_button_reading_cheesy_love_14.setObjectName("push_button_reading_cheesy_love_14")
        self.label_21 = QtWidgets.QLabel(Form)
        self.label_21.setGeometry(QtCore.QRect(1934, 124, 25, 25))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color: rgb(166, 166, 166);")
        self.label_21.setObjectName("label_21")
        self.label_24 = QtWidgets.QLabel(Form)
        self.label_24.setGeometry(QtCore.QRect(1670, 32, 131, 21))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("border: 0px solid #FF8D16;\n"
"border-radius: 0px;\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_24.setObjectName("label_24")
        self.line_15 = QtWidgets.QFrame(Form)
        self.line_15.setGeometry(QtCore.QRect(1600, 64, 6, 42))
        self.line_15.setStyleSheet("    border-style: solid;\n"
"    border-radius: 3px;\n"
"    color: rgba(255, 139, 42,0.8);\n"
"    border-color: rgba(255, 139, 42, 0.8);\n"
"    background-color: rgba(255, 139, 42,0.8);")
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.push_button_reading_cheesy_love_12 = QtWidgets.QPushButton(Form)
        self.push_button_reading_cheesy_love_12.setGeometry(QtCore.QRect(1627, 9, 18, 18))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.push_button_reading_cheesy_love_12.setFont(font)
        self.push_button_reading_cheesy_love_12.setStyleSheet("    border-style: solid;\n"
"    border-radius: 9px;\n"
"    border: 0px groove #000;\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgba(0, 0, 0, 0.5);\n"
"    background-color: rgba(0, 0, 0, 0.5);")
        self.push_button_reading_cheesy_love_12.setIconSize(QtCore.QSize(14, 14))
        self.push_button_reading_cheesy_love_12.setObjectName("push_button_reading_cheesy_love_12")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(1647, 26, 31, 31))
        font = QtGui.QFont()
        font.setFamily("华文仿宋")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_23.setObjectName("label_23")
        self.line_11 = QtWidgets.QFrame(Form)
        self.line_11.setGeometry(QtCore.QRect(1598, 59, 370, 1))
        self.line_11.setStyleSheet("    color: rgba(200, 200, 200, 0.3);\n"
"    border-color: rgba(200, 200, 200, 0.3);\n"
"    background-color: rgba(200, 200, 200, 0.3);")
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(1652, 74, 231, 21))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("border: 0px solid #FF8D16;\n"
"border-radius: 0px;\n"
"background-color: rgba(0, 0, 0, 0);")
        self.label_17.setObjectName("label_17")
        self.push_button_auto_start = QtWidgets.QPushButton(Form)
        self.push_button_auto_start.setGeometry(QtCore.QRect(382, 890, 51, 71))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.push_button_auto_start.setFont(font)
        self.push_button_auto_start.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    border-color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgba(255, 255, 255, 0.5);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.push_button_auto_start.setObjectName("push_button_auto_start")
        self.push_button_auto_start.raise_()
        self.push_button_reading_cheesy_love_12.raise_()
        self.push_button_exit.raise_()
        self.push_button_drink.raise_()
        self.push_button_setting.raise_()
        self.push_button_todo.raise_()
        self.push_button_weibo_info.raise_()
        self.push_button_about.raise_()
        self.push_button_novel.raise_()
        self.push_button_game.raise_()
        self.push_button_looking.raise_()
        self.push_button_60s_news.raise_()
        self.push_button_reading.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.push_button_schedule.raise_()
        self.label_5.raise_()
        self.date_label.raise_()
        self.weather_image_label_1.raise_()
        self.weather_image_label_2.raise_()
        self.weather_image_label_3.raise_()
        self.weather_image_label_4.raise_()
        self.weather_image_label_5.raise_()
        self.weather_info_label_2.raise_()
        self.weather_temp_label_2.raise_()
        self.weather_info_label_3.raise_()
        self.weather_temp_label_3.raise_()
        self.weather_info_label_4.raise_()
        self.weather_temp_label_4.raise_()
        self.weather_info_label_5.raise_()
        self.weather_temp_label_5.raise_()
        self.weather_info_label_1.raise_()
        self.weather_temp_label_1.raise_()
        self.daily_schedule_label.raise_()
        self.push_button_info.raise_()
        self.scroll_area.raise_()
        self.push_button_restart.raise_()
        self.label_add.raise_()
        self.center_label_2.raise_()
        self.looking_area.raise_()
        self.reading_area.raise_()
        self.push_button_schedule_2.raise_()
        self.push_button_schedule_3.raise_()
        self.push_button_schedule_4.raise_()
        self.line_top_2.raise_()
        self.time_label.raise_()
        self.top_area.raise_()
        self.push_button_copy_bottom.raise_()
        self.todo_area.raise_()
        self.line_2.raise_()
        self.daily_schedule_today.raise_()
        self.line_3.raise_()
        self.weather_position_label.raise_()
        self.push_button_drinking_history.raise_()
        self.push_button_drinking_setting.raise_()
        self.scrollArea.raise_()
        self.label_18.raise_()
        self.line_17.raise_()
        self.label_20.raise_()
        self.push_button_reading_cheesy_love_13.raise_()
        self.line_12.raise_()
        self.line_14.raise_()
        self.label_16.raise_()
        self.label_19.raise_()
        self.push_button_reading_cheesy_love_14.raise_()
        self.label_21.raise_()
        self.label_24.raise_()
        self.line_15.raise_()
        self.label_23.raise_()
        self.line_11.raise_()
        self.label_17.raise_()

        self.retranslateUi(Form)
        self.weibo_text_browser.anchorClicked['QUrl'].connect(Form.click_textbrowser) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.date_label.setText(_translate("Form", "2023年02月04日\n"
"癸卯兔年 农历正月十四\n"
"水瓶座 第 5 周 立春"))
        self.time_label.setText(_translate("Form", "00:00:00"))
        self.push_button_reading.setText(_translate("Form", "读的"))
        self.push_button_60s_news.setText(_translate("Form", "秒读"))
        self.push_button_weibo_info.setText(_translate("Form", "热搜"))
        self.weather_info_label_2.setText(_translate("Form", "23日 小到中\n"
"雨转中到大雨"))
        self.weather_temp_label_2.setText(_translate("Form", "1℃--17℃"))
        self.weather_info_label_3.setText(_translate("Form", "23日 小到中\n"
"雨转中到大雨"))
        self.weather_temp_label_3.setText(_translate("Form", "1℃--17℃"))
        self.weather_info_label_4.setText(_translate("Form", "23日 小到中\n"
"雨转中到大雨"))
        self.weather_temp_label_4.setText(_translate("Form", "1℃--17℃"))
        self.weather_info_label_5.setText(_translate("Form", "23日 小到中\n"
"雨转中到大雨"))
        self.weather_temp_label_5.setText(_translate("Form", "1℃--17℃"))
        self.weather_info_label_1.setText(_translate("Form", "小到中雨转中到大雨"))
        self.weather_temp_label_1.setText(_translate("Form", "1℃--17℃"))
        self.daily_schedule_label.setText(_translate("Form", "周六：双休日\n"
"周日：调休日（工作日）\n"
"周一：工作日\n"
"周二：工作日\n"
"周三：节假日"))
        self.push_button_looking.setText(_translate("Form", "看的"))
        self.label_add.setText(_translate("Form", "＋"))
        self.push_button_looking_fish.setText(_translate("Form", "摸鱼人日历"))
        self.push_button_looking_everyday.setText(_translate("Form", "必应每日一图"))
        self.push_button_reading_life.setText(_translate("Form", "生活小窍门"))
        self.push_button_reading_history.setText(_translate("Form", "历史上的今天"))
        self.push_button_reading_rainbow.setText(_translate("Form", "彩虹屁"))
        self.push_button_reading_riddle.setText(_translate("Form", "脑筋急转弯"))
        self.push_button_reading_morning.setText(_translate("Form", "早安心语"))
        self.push_button_reading_night.setText(_translate("Form", "晚安心语"))
        self.push_button_reading_chicken_1.setText(_translate("Form", "毒鸡汤①"))
        self.push_button_reading_chicken_2.setText(_translate("Form", "毒鸡汤②"))
        self.push_button_reading_cheesy_love.setText(_translate("Form", "土味情话"))
        self.push_button_todo.setText(_translate("Form", "待办"))
        self.push_button_novel.setText(_translate("Form", "小说"))
        self.push_button_game.setText(_translate("Form", "游戏"))
        self.push_button_setting.setText(_translate("Form", "设置"))
        self.push_button_about.setText(_translate("Form", "关于"))
        self.weibo_text_browser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'思源黑体\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p></body></html>"))
        self.push_button_top_baidu.setText(_translate("Form", "百度"))
        self.push_button_top_tencent.setText(_translate("Form", "腾讯"))
        self.push_button_top_douyin.setText(_translate("Form", "抖音"))
        self.push_button_top_zhihu.setText(_translate("Form", "知乎"))
        self.push_button_top_bilibili.setText(_translate("Form", "B站"))
        self.push_button_top_weibo.setText(_translate("Form", "微博"))
        self.push_button_top_refresh.setText(_translate("Form", "⟳刷新"))
        self.push_button_todo_ok.setText(_translate("Form", "完成"))
        self.push_button_todo_todo.setText(_translate("Form", "待办"))
        self.push_button_todo_add.setText(_translate("Form", "＋"))
        self.daily_schedule_today.setText(_translate("Form", "今天：工作日"))
        self.weather_position_label.setText(_translate("Form", "◉ 杭州"))
        self.push_button_exit.setText(_translate("Form", "退出"))
        self.label_18.setText(_translate("Form", "今天要把XXXX任务完成XXXXX"))
        self.label_20.setText(_translate("Form", "×"))
        self.label_16.setText(_translate("Form", "今天要把XXXX任务完成XXXXX"))
        self.label_19.setText(_translate("Form", "×"))
        self.label_21.setText(_translate("Form", "×"))
        self.label_24.setText(_translate("Form", "2024年5月7日 00:00"))
        self.push_button_reading_cheesy_love_12.setText(_translate("Form", "✓"))
        self.label_23.setText(_translate("Form", "🔔"))
        self.label_17.setText(_translate("Form", "今天要把XXXX任务完成XXXXX"))
        self.push_button_auto_start.setText(_translate("Form", "设置\n"
"开机\n"
"启动"))
