# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'city_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(234, 248)
        self.scroll_area = QtWidgets.QScrollArea(Form)
        self.scroll_area.setGeometry(QtCore.QRect(7, 32, 218, 201))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        self.scroll_area.setFont(font)
        self.scroll_area.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgba(255, 255, 255, 1);\n"
"    background-color: rgba(255, 255, 255, 1);")
        self.scroll_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scroll_area.setLineWidth(1)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 216, 199))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setGeometry(QtCore.QRect(20, 95, 61, 21))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.combo_box_county = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.combo_box_county.setGeometry(QtCore.QRect(82, 93, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combo_box_county.setFont(font)
        self.combo_box_county.setStyleSheet("    border-style: solid;\n"
"    border-radius: 3px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);")
        self.combo_box_county.setObjectName("combo_box_county")
        self.combo_box_province = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.combo_box_province.setGeometry(QtCore.QRect(82, 13, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combo_box_province.setFont(font)
        self.combo_box_province.setStyleSheet("    border-style: solid;\n"
"    border-radius: 3px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);")
        self.combo_box_province.setObjectName("combo_box_province")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setGeometry(QtCore.QRect(20, 55, 61, 21))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.push_button_ok = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.push_button_ok.setGeometry(QtCore.QRect(70, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.push_button_ok.setFont(font)
        self.push_button_ok.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 0px groove gray;\n"
"    color: #FFFFFF;\n"
"    border-color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgba(255, 255, 255, 0.5);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px groove gray;\n"
"}")
        self.push_button_ok.setObjectName("push_button_ok")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(20, 15, 61, 21))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.combo_box_city = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.combo_box_city.setGeometry(QtCore.QRect(82, 53, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.combo_box_city.setFont(font)
        self.combo_box_city.setStyleSheet("    border-style: solid;\n"
"    border-radius: 3px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);")
        self.combo_box_city.setObjectName("combo_box_city")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(10, 130, 191, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.push_button_60s_news = QtWidgets.QPushButton(Form)
        self.push_button_60s_news.setGeometry(QtCore.QRect(20, 5, 81, 35))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        self.push_button_60s_news.setFont(font)
        self.push_button_60s_news.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    border-color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"}")
        self.push_button_60s_news.setObjectName("push_button_60s_news")
        self.push_button_60s_news.raise_()
        self.scroll_area.raise_()

        self.retranslateUi(Form)
        self.combo_box_province.currentTextChanged['QString'].connect(Form.slot_province_click) # type: ignore
        self.combo_box_city.currentTextChanged['QString'].connect(Form.slot_city_click) # type: ignore
        self.push_button_ok.clicked.connect(Form.push_button_ok_click) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_13.setText(_translate("Form", "选择市："))
        self.label_12.setText(_translate("Form", "选择市："))
        self.push_button_ok.setText(_translate("Form", "确定"))
        self.label_11.setText(_translate("Form", "选择省："))
        self.label.setText(_translate("Form", "如果选择出现问题请尝试重启软件"))
        self.push_button_60s_news.setText(_translate("Form", "选择城市"))
