# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_todo_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(387, 421)
        self.scroll_area = QtWidgets.QScrollArea(Form)
        self.scroll_area.setGeometry(QtCore.QRect(7, 32, 371, 381))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        self.scroll_area.setFont(font)
        self.scroll_area.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgba(255, 255, 255, 1);\n"
"    background-color: rgba(255, 255, 255, 1);")
        self.scroll_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scroll_area.setLineWidth(1)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 369, 379))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.text_edit_des = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.text_edit_des.setGeometry(QtCore.QRect(13, 90, 341, 121))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.text_edit_des.setFont(font)
        self.text_edit_des.setStyleSheet("    border-style: solid;\n"
"    border-radius: 3px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);")
        self.text_edit_des.setObjectName("text_edit_des")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setGeometry(QtCore.QRect(13, 222, 81, 18))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("    color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0);")
        self.label_12.setObjectName("label_12")
        self.push_button_cancel = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.push_button_cancel.setGeometry(QtCore.QRect(73, 344, 51, 25))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.push_button_cancel.setFont(font)
        self.push_button_cancel.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 0px groove gray;\n"
"    color: #FFFFFF;\n"
"    border-color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgba(255, 255, 255, 0.5);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px groove gray;\n"
"}")
        self.push_button_cancel.setObjectName("push_button_cancel")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(13, 68, 45, 18))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("    color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0);")
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(13, 13, 45, 18))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("    color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0);")
        self.label_8.setObjectName("label_8")
        self.push_button_success = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.push_button_success.setGeometry(QtCore.QRect(233, 344, 51, 25))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.push_button_success.setFont(font)
        self.push_button_success.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 0px groove gray;\n"
"    color: #FFFFFF;\n"
"    border-color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgba(255, 255, 255, 0.5);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px groove gray;\n"
"}")
        self.push_button_success.setObjectName("push_button_success")
        self.combo_box_degree = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.combo_box_degree.setGeometry(QtCore.QRect(13, 244, 341, 22))
        font = QtGui.QFont()
        font.setFamily("思源黑体 Normal")
        self.combo_box_degree.setFont(font)
        self.combo_box_degree.setStyleSheet("    border-style: solid;\n"
"    border-radius: 3px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);")
        self.combo_box_degree.setObjectName("combo_box_degree")
        self.combo_box_degree.addItem("")
        self.combo_box_degree.addItem("")
        self.combo_box_degree.addItem("")
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(13, 274, 81, 18))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("    color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0);")
        self.label_11.setObjectName("label_11")
        self.line_edit_title = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.line_edit_title.setGeometry(QtCore.QRect(13, 35, 341, 25))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        self.line_edit_title.setFont(font)
        self.line_edit_title.setStyleSheet("    border-style: solid;\n"
"    border-radius: 3px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);")
        self.line_edit_title.setObjectName("line_edit_title")
        self.check_push_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.check_push_button.setGeometry(QtCore.QRect(15, 298, 18, 18))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(9)
        self.check_push_button.setFont(font)
        self.check_push_button.setStyleSheet("border-style: solid;\n"
"border-radius: 9px;\n"
"border: 1px groove #000;\n"
"color: rgb(255, 255, 255);\n"
"border-color: rgba(0, 0, 0, 0.5);\n"
"background-color: rgb(255, 255, 255);")
        self.check_push_button.setText("")
        self.check_push_button.setIconSize(QtCore.QSize(14, 14))
        self.check_push_button.setObjectName("check_push_button")
        self.date_time_edit = QtWidgets.QDateTimeEdit(self.scrollAreaWidgetContents)
        self.date_time_edit.setGeometry(QtCore.QRect(43, 296, 311, 22))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        self.date_time_edit.setFont(font)
        self.date_time_edit.setStyleSheet("    border-style: solid;\n"
"    border-radius: 3px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);")
        self.date_time_edit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.date_time_edit.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.date_time_edit.setCalendarPopup(False)
        self.date_time_edit.setObjectName("date_time_edit")
        self.scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.push_button_60s_news = QtWidgets.QPushButton(Form)
        self.push_button_60s_news.setGeometry(QtCore.QRect(20, 5, 101, 35))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        self.push_button_60s_news.setFont(font)
        self.push_button_60s_news.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    border-color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"}")
        self.push_button_60s_news.setObjectName("push_button_60s_news")
        self.push_button_60s_news.raise_()
        self.scroll_area.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_12.setText(_translate("Form", "程度："))
        self.push_button_cancel.setText(_translate("Form", "取消"))
        self.label_9.setText(_translate("Form", "内容："))
        self.label_8.setText(_translate("Form", "标题："))
        self.push_button_success.setText(_translate("Form", "确定"))
        self.combo_box_degree.setItemText(0, _translate("Form", "紧急"))
        self.combo_box_degree.setItemText(1, _translate("Form", "一般"))
        self.combo_box_degree.setItemText(2, _translate("Form", "莫慌"))
        self.label_11.setText(_translate("Form", "闹钟："))
        self.date_time_edit.setDisplayFormat(_translate("Form", "yyyy-MM-dd HH:mm"))
        self.push_button_60s_news.setText(_translate("Form", "新增待办事项"))
