# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'record_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(232, 461)
        self.scroll_area = QtWidgets.QScrollArea(Form)
        self.scroll_area.setGeometry(QtCore.QRect(7, 32, 218, 421))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        self.scroll_area.setFont(font)
        self.scroll_area.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgba(255, 255, 255, 1);\n"
"    background-color: rgba(255, 255, 255, 1);")
        self.scroll_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scroll_area.setLineWidth(1)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 216, 419))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.drink_table_view = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.drink_table_view.setGeometry(QtCore.QRect(10, 20, 191, 391))
        self.drink_table_view.setObjectName("drink_table_view")
        self.scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.push_button_60s_news = QtWidgets.QPushButton(Form)
        self.push_button_60s_news.setGeometry(QtCore.QRect(20, 5, 81, 35))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        self.push_button_60s_news.setFont(font)
        self.push_button_60s_news.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    border-color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"}")
        self.push_button_60s_news.setObjectName("push_button_60s_news")
        self.push_button_60s_news.raise_()
        self.scroll_area.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.push_button_60s_news.setText(_translate("Form", "喝水记录"))
