# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setting_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(237, 191)
        self.scroll_area = QtWidgets.QScrollArea(Form)
        self.scroll_area.setGeometry(QtCore.QRect(7, 32, 221, 151))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        self.scroll_area.setFont(font)
        self.scroll_area.setStyleSheet("    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgba(255, 255, 255, 1);\n"
"    background-color: rgba(255, 255, 255, 1);")
        self.scroll_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scroll_area.setLineWidth(1)
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 219, 149))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(20, 60, 71, 21))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.spin_box_drinking_count = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spin_box_drinking_count.setGeometry(QtCore.QRect(90, 20, 41, 25))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        self.spin_box_drinking_count.setFont(font)
        self.spin_box_drinking_count.setStyleSheet("    border-style: solid;\n"
"    border-radius: 3px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);")
        self.spin_box_drinking_count.setMinimum(1)
        self.spin_box_drinking_count.setMaximum(100)
        self.spin_box_drinking_count.setObjectName("spin_box_drinking_count")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(31, 20, 61, 21))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(134, 20, 41, 21))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.combo_box_view_message = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.combo_box_view_message.setGeometry(QtCore.QRect(100, 60, 91, 22))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        self.combo_box_view_message.setFont(font)
        self.combo_box_view_message.setStyleSheet("    border-style: solid;\n"
"    border-radius: 3px;\n"
"    border: 1px groove gray;\n"
"    color: rgb(0, 0, 0);\n"
"    border-color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 255, 255);")
        self.combo_box_view_message.setObjectName("combo_box_view_message")
        self.combo_box_view_message.addItem("")
        self.combo_box_view_message.addItem("")
        self.push_button_ok = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.push_button_ok.setGeometry(QtCore.QRect(70, 100, 71, 23))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(10)
        self.push_button_ok.setFont(font)
        self.push_button_ok.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    border: 0px groove gray;\n"
"    color: #FFFFFF;\n"
"    border-color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgba(255, 255, 255, 0.5);\n"
"    color: rgb(0, 0, 0);\n"
"    border: 1px groove gray;\n"
"}")
        self.push_button_ok.setObjectName("push_button_ok")
        self.label_9.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.combo_box_view_message.raise_()
        self.push_button_ok.raise_()
        self.spin_box_drinking_count.raise_()
        self.scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.push_button_60s_news = QtWidgets.QPushButton(Form)
        self.push_button_60s_news.setGeometry(QtCore.QRect(20, 5, 81, 35))
        font = QtGui.QFont()
        font.setFamily("思源黑体")
        font.setPointSize(11)
        self.push_button_60s_news.setFont(font)
        self.push_button_60s_news.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-radius: 10px;\n"
"    color: #FFFFFF;\n"
"    border-color: #000000;\n"
"    background-color: rgba(0, 0, 0, 0.3);\n"
"}")
        self.push_button_60s_news.setObjectName("push_button_60s_news")
        self.push_button_60s_news.raise_()
        self.scroll_area.raise_()

        self.retranslateUi(Form)
        self.push_button_ok.clicked.connect(Form.push_button_ok_click)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_9.setText(_translate("Form", "界面显示："))
        self.label.setText(_translate("Form", "我要喝"))
        self.label_2.setText(_translate("Form", "杯水"))
        self.combo_box_view_message.setItemText(0, _translate("Form", "正着计数"))
        self.combo_box_view_message.setItemText(1, _translate("Form", "倒着计数"))
        self.push_button_ok.setText(_translate("Form", "确定"))
        self.push_button_60s_news.setText(_translate("Form", "喝水设置"))
